modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"

[[mods]]
modId="aether_redux"
version="${mod_version}"
displayName="${mod_name}"
displayURL = "https://github.com/Zepalesque/The-Aether-Redux"
logoFile = "redux.png"
authors = "Zepalesque"
description = '''
Zenith is a library designed to simplify a variety of tedious processes in a way that is dynamic and easily expandable, along with adding useful APIs that can be used for mods.

The main reason the mod exists is for the Aether: Redux, but it may be used in the future, and may be useful as well.
 '''
[[dependencies.aether_redux]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[20.4.167,)"
ordering="NONE"
side="BOTH"

[[dependencies.aether_redux]]
modId="minecraft"
type="required" #mandatory
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.aether_redux]]
modId="zenith"
type="required" #mandatory
versionRange="[${zenith_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.aether_redux]]
modId = "aether"
type="required" #mandatory
versionRange = "[${mc_version}-,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.aether_redux]]
modId = "aeroblender"
type="required" #mandatory
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"